server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db2019?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001   #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/get/**   #断言,路径相匹配的进行路由
        - id: payment_routh2
          #uri: http://localhost:8001   #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/getPort/**   #断言,路径相匹配的进行路由
            #- After=2020-03-16T15:39:29.060+08:00[Asia/Shanghai] #在这个时间之后的生效。假如当前时间2020-03-16T15:50则访问成功，2020-03-16T14:50则路由失败,相当于sql的where条件
            #- Before=2020-03-16T15:39:29.060+08:00[Asia/Shanghai] #和after相反。在这个时间之前的路由生效，之后的不生效
            - Between=2020-03-16T14:39:29.060+08:00[Asia/Shanghai]  ,  2020-03-16T15:39:29.060+08:00[Asia/Shanghai] #在这两个时间内的路由请求可以成功
mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.sykean.springcloud.entity
eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka
      #defaultZone: http://localhost:7001/eureka #单机版
      #defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #集群版



