server:
  port: 7002
eureka:
  instance:
    hostname: eureka7002.com #集群版
  # hostname: localhost #实例名称,单机版
  client:
    register-with-eureka: false #不向注册中心注册自己
    fetch-registry: false #false表示自己就是注册中心
    service-url:
      #设置与eureka server交互的地址查询服务和注册服务要依赖的地址
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/