server:
  port: 2003

spring:
  application:
    name: seata-account-service
  cloud:
    loadbalancer:
      retry:
        enabled: true
    alibaba:
      seata:
        tx-service-group: yh_tx_group
    nacos:
      discovery:
        server-addr: 192.168.20.152:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_account
    username: root
    password: 123456

feign:
  hystrix:
    enabled: false
ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 3000

logging:
  level:
    io:
      seata: info

mybatis:
  mapperLocations: classpath:mapper/*.xml



